import type { SimulationStatus, TCADParameter } from '../../shared/types.js';
import path from 'path';
import { getScriptById } from './scriptService.js';
import { vmTcadService } from './virtualMachineTCADService.js';

const simulations: Map<string, SimulationStatus> = new Map();
const simulationTimers: Map<string, ReturnType<typeof setInterval>> = new Map();

const TCAD_MODE = (process.env.TCAD_MODE as 'local' | 'ssh' | 'simulation') || 'simulation';

export async function runSimulation(scriptId: string, parameters: TCADParameter[]): Promise<string> {
  const simulationId = 'sim_' + Date.now();
  
  const status: SimulationStatus = {
    id: simulationId,
    status: 'running',
    progress: 0,
    logs: ['[INFO] Starting TCAD simulation...', '[INFO] Parsing input parameters...']
  };
  
  simulations.set(simulationId, status);
  
  if (TCAD_MODE === 'simulation') {
    simulateProgress(simulationId);
  } else {
    runVMTCADSimulation(simulationId, scriptId, parameters);
  }
  
  return simulationId;
}

async function runVMTCADSimulation(
  simulationId: string, 
  scriptId: string, 
  parameters: TCADParameter[]
): Promise<void> {
  const status = simulations.get(simulationId);
  if (!status) return;

  try {
    const script = getScriptById(scriptId);
    if (!script) {
      throw new Error('Script not found');
    }

    status.logs.push('[INFO] Initializing TCAD environment...');
    await vmTcadService.initialize();

    const simulationDir = scriptId;
    status.logs.push('[INFO] Writing script file...');
    const scriptName = script.type === 'sprocess' ? 'process.cmd' : 'simulation.cmd';
    const scriptPath = await vmTcadService.writeScript(script.content, scriptName, simulationDir);

    status.progress = 20;
    status.logs.push(`[INFO] Starting Sentaurus ${script.type}...`);

    const onLog = (log: string) => {
      status.logs.push(log);
    };

    let result;
    if (script.type === 'sdevice') {
      result = await vmTcadService.executeSdevice(scriptPath, onLog);
    } else if (script.type === 'sprocess') {
      result = await vmTcadService.executeSprocess(scriptPath, onLog);

      if (!result.success) {
        throw new Error(result.error || 'Virtual process execution failed');
      }

      status.progress = 60;
      status.logs.push('[INFO] Inspecting generated structure files...');
      const tdrFiles = await vmTcadService.listTDROutputs(simulationDir);
      if (tdrFiles.length === 0) {
        throw new Error('No .tdr structure files were generated by the process script.');
      }

      for (const tdrFile of tdrFiles) {
        const baseName = path.basename(tdrFile, '.tdr');
        status.logs.push(`[INFO] Running device simulation for structure ${baseName}...`);

        const deviceScript = createDeviceCommandContent(tdrFile, `${baseName}.plt`, `${baseName}.out`);
        const deviceScriptPath = await vmTcadService.writeScript(deviceScript, `device_${baseName}.cmd`, simulationDir);
        const deviceResult = await vmTcadService.executeSdevice(deviceScriptPath, onLog);

        if (!deviceResult.success) {
          throw new Error(deviceResult.error || `Device simulation failed for ${tdrFile}`);
        }
      }
    } else {
      throw new Error(`Unsupported script type: ${script.type}`);
    }

    if (!result.success) {
      throw new Error(result.error || 'TCAD execution failed');
    }

    status.progress = 80;
    status.logs.push('[INFO] Parsing simulation results...');

    const rawResults = await vmTcadService.parseResults(simulationDir);
    const metrics = await vmTcadService.extractMetrics(rawResults);
    
    status.progress = 100;
    status.status = 'completed';
    status.result = {
      id: simulationId,
      timestamp: Date.now(),
      data: metrics,
      charts: generateChartsFromMetrics(metrics),
      summary: 'Simulation completed successfully'
    };

    await vmTcadService.disconnect();

  } catch (error) {
    status.status = 'failed';
    status.progress = 100;
    status.logs.push(`[ERROR] ${error instanceof Error ? error.message : String(error)}`);
    
    try {
      await vmTcadService.disconnect();
    } catch (e) {
      console.error('Error disconnecting:', e);
    }
  }
}

function createDeviceCommandContent(tdrFile: string, pltFile: string, outFile: string): string {
  return `File {
  Grid = "${tdrFile}"
  Plot = "${pltFile}"
  Output = "${outFile}"
}

Physics {
  Models = { "Fermi" "SRH" "Auger" }
}

Solve {
  Coupled(Iterations = 100) {
    Poisson
    Electron
    Hole
  }
}
`;
}

function generateChartsFromMetrics(metrics: any): any[] {
  if (metrics.batchMetrics) {
    const entries = Object.entries(metrics.batchMetrics).map(([file, values], index) => ({
      name: file,
      index,
      thresholdVoltage: values.thresholdVoltage || 0,
      onCurrent: values.onCurrent || 0
    }));

    return [
      {
        type: 'line',
        title: 'On Current by Structure',
        xLabel: 'Structure Index',
        yLabel: 'On Current (A)',
        data: entries.map((entry) => ({ x: entry.index, y: entry.onCurrent }))
      },
      {
        type: 'line',
        title: 'Threshold Voltage by Structure',
        xLabel: 'Structure Index',
        yLabel: 'Threshold Voltage (V)',
        data: entries.map((entry) => ({ x: entry.index, y: entry.thresholdVoltage }))
      }
    ];
  }

  const ivData = [];
  for (let v = 0; v <= 1.0; v += 0.05) {
    const i = (metrics.onCurrent || 1e-4) * v * v + 1e-7 * v;
    ivData.push({ x: v, y: i });
  }

  const vtData = [];
  for (let vg = 0; vg <= 2.0; vg += 0.1) {
    const id = Math.max(0, vg - (metrics.thresholdVoltage || 0.7));
    vtData.push({ x: vg, y: id * id * 1e-4 });
  }

  return [
    {
      type: 'line',
      title: 'ID-VD Curve',
      xLabel: 'Drain Voltage (V)',
      yLabel: 'Drain Current (A)',
      data: ivData
    },
    {
      type: 'line',
      title: 'ID-VG Curve',
      xLabel: 'Gate Voltage (V)',
      yLabel: 'Drain Current (A)',
      data: vtData
    }
  ];
}

export async function getSimulationStatus(id: string): Promise<SimulationStatus> {
  const status = simulations.get(id);
  if (!status) {
    throw new Error('Simulation not found');
  }
  return status;
}

function simulateProgress(simulationId: string) {
  let progress = 0;
  const logs = [
    '[INFO] Initializing mesh...',
    '[INFO] Setting up doping profiles...',
    '[INFO] Calculating initial solution...',
    '[INFO] Solving Poisson equation...',
    '[INFO] Solving carrier continuity equations...',
    '[INFO] Running quasistationary sweep...',
    '[INFO] Processing intermediate results...',
    '[INFO] Finalizing simulation...',
    '[INFO] Saving output files...',
    '[SUCCESS] Simulation completed successfully!'
  ];
  
  const interval = setInterval(() => {
    progress += 10;
    const status = simulations.get(simulationId);
    if (status) {
      status.progress = progress;
      const logIndex = Math.floor(progress / 10) - 1;
      if (logIndex >= 0 && logIndex < logs.length) {
        status.logs.push(logs[logIndex]);
      }
      
      if (progress >= 100) {
        status.status = 'completed';
        status.result = generateMockResult(simulationId);
        clearInterval(interval);
        simulationTimers.delete(simulationId);
      }
    }
  }, 500);
  simulationTimers.set(simulationId, interval);
}

function clearSimulationTimer(simulationId: string) {
  const timer = simulationTimers.get(simulationId);
  if (timer) {
    clearInterval(timer);
    simulationTimers.delete(simulationId);
  }
}

export async function stopSimulation(simulationId: string): Promise<void> {
  const status = simulations.get(simulationId);
  if (!status) {
    throw new Error('Simulation not found');
  }

  clearSimulationTimer(simulationId);

  if (status.status === 'running') {
    status.status = 'failed';
    status.progress = 100;
    status.logs.push('[INFO] Simulation stopped by user.');
    delete status.result;
  }
}

export async function resetSimulation(simulationId: string): Promise<void> {
  const status = simulations.get(simulationId);
  if (!status) {
    throw new Error('Simulation not found');
  }

  clearSimulationTimer(simulationId);
  status.status = 'idle';
  status.progress = 0;
  status.logs = [];
  delete status.result;
}

function generateMockResult(simulationId: string) {
  const ivData = [];
  for (let v = 0; v <= 1.0; v += 0.05) {
    const i = 1e-6 * v * v + 1e-7 * v;
    ivData.push({ x: v, y: i });
  }
  
  const vtData = [];
  for (let vg = 0; vg <= 2.0; vg += 0.1) {
    const id = 1e-5 * Math.max(0, vg - 0.7) * Math.max(0, vg - 0.7);
    vtData.push({ x: vg, y: id });
  }
  
  return {
    id: simulationId,
    timestamp: Date.now(),
    data: {
      thresholdVoltage: 0.72,
      onCurrent: 1.23e-4,
      offCurrent: 2.45e-12,
      subthresholdSlope: 65,
      transconductance: 0.045
    },
    charts: [
      {
        type: 'line',
        title: 'ID-VD Curve',
        xLabel: 'Drain Voltage (V)',
        yLabel: 'Drain Current (A)',
        data: ivData
      },
      {
        type: 'line',
        title: 'ID-VG Curve',
        xLabel: 'Gate Voltage (V)',
        yLabel: 'Drain Current (A)',
        data: vtData
      }
    ],
    summary: '仿真完成！MOSFET器件表现正常。阈值电压Vth=0.72V，开态电流Ion=1.23e-4A，亚阈值摆幅SS=65mV/dec。器件性能符合设计预期。'
  };
}

export async function testScriptExecution(script: any): Promise<{
  success: boolean;
  message: string;
  error?: string;
  logs: string[];
}> {
  const logs: string[] = [];
  
  try {
    logs.push('[INFO] Initializing TCAD environment...');
    await vmTcadService.initialize();

    const testDir = `test_${Date.now()}`;
    logs.push('[INFO] Creating test directory...');
    
    const scriptName = script.type === 'sprocess' ? 'process.cmd' : 'simulation.cmd';
    logs.push(`[INFO] Writing ${script.type} script...`);
    
    const scriptPath = await vmTcadService.writeScript(script.content, scriptName, testDir);
    logs.push(`[INFO] Script written to: ${scriptPath}`);

    logs.push(`[INFO] Testing ${script.type} execution...`);
    
    let result;
    if (script.type === 'sdevice') {
      result = await vmTcadService.executeSdevice(scriptPath, (log) => logs.push(log));
    } else if (script.type === 'sprocess') {
      result = await vmTcadService.executeSprocess(scriptPath, (log) => logs.push(log));
    } else {
      throw new Error(`Unsupported script type: ${script.type}`);
    }

    if (result.success) {
      logs.push('[SUCCESS] Script execution test passed!');
      return {
        success: true,
        message: `${script.type.toUpperCase()} 脚本可以通过 SSH 成功执行！`,
        logs
      };
    } else {
      logs.push(`[ERROR] Script execution failed: ${result.error}`);
      return {
        success: false,
        message: `${script.type.toUpperCase()} 脚本执行失败`,
        error: result.error,
        logs
      };
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    logs.push(`[ERROR] Test failed: ${errorMessage}`);
    
    return {
      success: false,
      message: 'SSH 连接或脚本执行测试失败',
      error: errorMessage,
      logs
    };
  } finally {
    try {
      await vmTcadService.disconnect();
      logs.push('[INFO] Disconnected from virtual machine');
    } catch (e) {
      logs.push(`[WARNING] Error disconnecting: ${e}`);
    }
  }
}
